### ISSUE TITLE
Coins always split

### ISSUE THREAD

**Issue by MartijnKluijtmans** [zPools/sonoa#4]
On https://github.com/zPools/sonoa/blob/master/src/wallet.cpp#L3310
if (GetWeight(block.GetBlockTime(), (int64_t)txNew.nTime) < nStakeSplitAge)
with nStakeSplitAge == 365 * 24 * 60 * 60;
This is always true, so coins always splits, normally not a problem, but with nMinimumInputValue = 50; Coin parts can go below 50 and so stop staking.
If L3310 change to "'if(nCredit > 1000 * COIN)" Like sono version 1.4.
Coins split only if > 1000 and enough blocks are available for PoW.

**Comment by zPools** [comment]
Hey, you can look in the branch "pos"

Currently testing in testnet seems to work like charm. 

Will be included in next release

**Comment by zPools** [comment]
Will be fixed with #5
